theme: minima


show_excerpts: false

header_pages:
  - about.md


linkedin_username: maninambi

plugins:
  - jekyll-seo-tag

disqus:
    shortname: mnambi

google_analytics: UA-119135377-1










