theme: minima
title: ["Hi, I am Mani."]
description: ["I teach robots to do useful things."]

show_excerpts: false

header_pages:
  - about.md

plugins:
  - jekyll-seo-tag


google_analytics: UA-119135377-1










