theme: minima
title: "Manikantan Nambi"
author: "Manikantan Nambi"

show_excerpts: false

header_pages: 
    - about.md

linkedin_username: maninambi

plugins:
  - jekyll-seo-tag

disqus:
    shortname: mnambi

google_analytics: UA-119135377-1










